repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^src/go/pylon/testdata/.*\.(ascii|svg)$
      - id: trailing-whitespace
        exclude: ^src/go/pylon/testdata/.*\.(ascii|svg)$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint-fix
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
